spring:
  application:
    name: FinancialServices
  config:
    import: optional:configserver:http://localhost:9050
  profiles:
    active: default
server:
  port: 9060
service:
  collateral:
    host: localhost
    port: 9070
  product:
    host: localhost
    port: 9080
  user:
    host: localhost
    port: 9090
management:
  endpoints:
    web:
      exposure:
        include: "*"